### ISSUE TITLE
Make cy.wrap waiting timeout configurable or use default

### ISSUE THREAD

**Issue by ttomaszewski** [bahmutov/cypress-network-idle#10]
While using this plugin, we are experiencing a lot of timeouts on, https://github.com/bahmutov/cypress-network-idle/blob/304dd6933fd396922b8ad271b4d7c5f42900c3cc/src/index.js#L8

Is there a way we can make this configurable or use the defaultCommandTimeout setting? This should be plenty of time but CI network can be really slow, so we are hitting the "Network is busy" often. 

We can increase `timeLimitMs` but this causes more general slowness in test suite completion.

**Comment by bahmutov** [comment]
I would welcome a pull request to make this configurable

**Comment by Hypercubed** [comment]
@bahmutov @ttomaszewski Do I understand this correctly?  A call to `cy.waitForNetworkIdle(X)` will wait for the network to be idle for at least `X` ms before moving on.  If the network is not idle at all within `3*X` ms then a "Network is busy" error is thrown and the test is failed?

Assuming that's correct what is the desired behavior:

1) Allow the timeout to be configureable (`cy.waitForNetworkIdle(X, { timeout: Y })`) after which an error is throw and the test fails.

and/or

2) Allow the test to continue once a maximum time is exceeded (`cy.waitForNetworkIdle(X, Y)`) without failing the test.

**Comment by bahmutov** [comment]
:) I do like failing the test if the network does not “idle”

**Comment by Hypercubed** [comment]
A fix for this has been merged.  Pending release.

**Comment by Hypercubed** [comment]
I don't know how to trigger a release on this repo :(

**Comment by bahmutov** [comment]
Hmm, I guess it did not do semantic release when the commit had `Feature: ...` let me push an empty commit to close this and release
