### ISSUE TITLE
waitForNetworkIdle should resolve the the waiting if network becomes idle before given timeout

### ISSUE THREAD

**Issue by gurudattgd04** [bahmutov/cypress-network-idle#21]
What I have observed is the function waitForNetworkIdle waits for the given timeout even though network becomes idle.

I'm not sure if this is done by purpose and hence wanted to check.

It would be better if we resolve the function based on OR condition, if the network becomes idle before the timeout then resolve it if not then wait for maximum timeout and then throw error

**Comment by bahmutov** [comment]
So something like: if there are any pending requests, wait for them. Or wait for new requests or no requests for N seconds?

**Comment by bahmutov** [comment]
Closing as not enough information provided
