### ISSUE TITLE
Method patterns are not wokring

### ISSUE THREAD

**Issue by ApostolosBenisis** [bahmutov/cypress-network-idle#26]
Passing a pattern as a method argument results in an error
The following examples fail e.g:
`cy.waitForNetworkIdle('*', 2000) `
`cy.waitForNetworkIdle('/GET|POST/', 2000)`
`cy.waitForNetworkIdle('+(GET|POST)', 2000)`

**Comment by bahmutov** [comment]
Released in v1.5.0
