### ISSUE TITLE
Sometimes `cy.waitForNetworkIdle` does wait for timeout

### ISSUE THREAD

**Issue by Hypercubed** [bahmutov/cypress-network-idle#31]
Sometimes (intermittently on CI for me) I see that the `cy.waitForNetworkIdle` command doesn't wait the full `timeout` before failing.  As you see in the images below the command timeout is 60000 ms, but the command failed after 27 ms with the "Network is busy" error.  This occurs intermittently on a single particular test only on CI headless.

I'm at a loss on what's happening here.  I suspect that something else in the test might be failing but the `cypress-network-idle` error is being shown and the other error is being swallowed.  Is there another mechanism we can use instead of the repeatedly calling `throw new Error('Network is busy')`?  Has anyone else experienced this?

![image](https://user-images.githubusercontent.com/509946/165983056-0a7de0e4-96bb-4fd7-8fd2-e11ddfbb71b0.png)

![image](https://user-images.githubusercontent.com/509946/165983066-387e5e32-9bca-43ee-a7a4-b90da4dd7298.png)

**Comment by bahmutov** [comment]
Hmm never seen this, any particular situation this happens? Any messages in the devtools console?

**Comment by Hypercubed** [comment]
It seams (and there is a lot of guessing here) that it happens when there are pending requests (kicked off in a previous test) and the `cy.waitForNetworkIdle` is in an `after`.

**Comment by bahmutov** [comment]
Ok, I just merged a PR that IF there are current pending requests (probably because you used `prepare`) then it waits for them and then for N seconds of idle

**Comment by Hypercubed** [comment]
I think the issue is that when `cy.waitForNetworkIdle` is inside an `after` it runs even if the test failed (as it should) but doesn't wait for the full timeout...

Here is a repo using kitchen-sink:

```
describe('example to-do app', () => {
  beforeEach(() => {
    cy.visit('http://localhost:8080/todo')
  })

  it('displays two todo items by default', () => {
    cy.get('.todo-list li').last().then(($el) => {
      expect($el).to.contain('Walk the dog')
      expect($el).to.contain('Walk the cat') // this causes the test to fail
    })
  })

  after(() => {
    cy.waitForNetworkIdle(2000)
  })
})
```

When `expect($el).to.contain('Walk the cat')` is uncommented the test fails AND the `after` fails.  The UI makes it look like the failure is because the "Network is busy":

![image](https://user-images.githubusercontent.com/509946/168391499-7aea2a51-5912-4f3a-ab8b-fc2e9e69e261.png)

If we uncomment that line, `waitForNetworkIdle` waits the correct amount of time:

![image](https://user-images.githubusercontent.com/509946/168391627-cca8c7c1-abe0-4fd6-9898-93919ab42363.png)

**Comment by Hypercubed** [comment]
Thinking we need to try something that doesn't throw until the timeout is exceeded.  Something like:

```
  const interval = Math.max(timeout / 10, 100)

  cy.log(`nnetwork idle for ${timeLimitMs} ms (timeout: ${timeout} ms)`)
  cy.wrap('waiting...', { timeout: timeout })
    .should(() => {
      return new Promise((resolve, reject) => {
        const timer = setInterval(() => {
          const d = +new Date()
          const t = counters.lastNetworkAt || counters.started
          const waited = d - counters.started
          const elapsed = d - t

          console.log({waited});

          if (elapsed < timeLimitMs) {
            if (elapsed > timeout) {
              clearInterval(timer);
              reject(new Error(`Network is busy. Failed after ${waited} ms`))
            }
            // retries
          } else {
            clearInterval(timer);
            resolve();
          }
        }, interval);
      });
    })
```

**Comment by Hypercubed** [comment]
```ts
      return new Promise((resolve, reject) => {
        const timer = setInterval(() => {
          const d = +new Date()
          const t = counters.lastNetworkAt || counters.started
          const waited = d - counters.started
          const elapsed = d - t

          if (waited > timeout) {
            clearInterval(timer);
            reject(new Error(`Network is busy. Failed after ${waited} ms`))
          }

          if (elapsed > timeLimitMs) {
            counters.finished = d
            clearInterval(timer)
            resolve()
          }
        }, interval);
      });
```

**Comment by Hypercubed** [comment]
The code above seams to be working great for me.  I can do a PR... but really curious why the existing code doesn't retry inside the after when there is an exiting error.
