### ISSUE TITLE
intermittent timeout occurs if a request is aborted

### ISSUE THREAD

**Issue by ridakk** [bahmutov/cypress-network-idle#43]
when a request is cancelled (for our case, request is aborted by client not server), intermittently plugin fails to capture request end and so it gives timeout error.
https://axios-http.com/docs/cancellation

@bahmutov if you can lead me, i can try to create a PR. i had to revert back the plugin usage as it is causing intermittent failures but i can prepare a test setup to reproduce the issue locally for myself.

**Comment by bahmutov** [comment]
See if you can recreate the situation in a test and then we can figure out the solution

**Comment by ridakk** [comment]
@bahmutov it seems like the issue is caused because of my wrong usage of the plugin and the intercept matchers 🤕 

thx for the prompt response any way 🙇
